// GENERATED by scripts/build-art-manifest.ts. Do not edit by hand.
import type { ImageSource } from 'expo-image';

export type ArtKind =
  | 'races'
  | 'classes'
  | 'schools'
  | 'backgrounds'
  | 'items'
  | 'portraits'
  | 'subclasses'
  | 'sigils'
  | 'ancestries';

export type ArtAsset = { source: ImageSource | number; blurhash: string };

const ENTRIES: [ArtKind, string, number, string][] = [
  ['backgrounds', 'acolyte', require('../../../assets/art/backgrounds/acolyte.webp'), 'UnMQU^xa~W%Lofj[t6of_2WCM{t6t6ayfkj['],
  ['backgrounds', 'custom', require('../../../assets/art/backgrounds/custom.webp'), 'UjMjQ?j]-o-o%2WBazt6~Vt6aeWCflt6ocRk'],
  ['classes', 'barbarian', require('../../../assets/art/classes/barbarian.webp'), 'UrMs}{xa~WxuoJj[ofj@~WofIojtxaayj[ay'],
  ['classes', 'bard', require('../../../assets/art/classes/bard.webp'), 'UdK,{Lf%~U%Ls:WVofjb^*s:Rkj[t5oLafkB'],
  ['classes', 'cleric', require('../../../assets/art/classes/cleric.webp'), 'UwNJm:xt^*xaxZoeWCR*~VofM{j[t6ays:of'],
  ['classes', 'druid', require('../../../assets/art/classes/druid.webp'), 'UCHxcza1%2~o?Z%3kBW-~V-.00M}?HIoM|n,'],
  ['classes', 'fighter', require('../../../assets/art/classes/fighter.webp'), 'UjNJq3WB~V-:xaaykCs:~Vt6M|WB%Lj[jaWV'],
  ['classes', 'monk', require('../../../assets/art/classes/monk.webp'), 'UjNc=zs:^*%Lt6ayofj[~VoeE2bHs:f6oekB'],
  ['classes', 'paladin', require('../../../assets/art/classes/paladin.webp'), 'USMZ,R$~}=_M^*ofxaoe}=x]9bMx-oayM{js'],
  ['classes', 'ranger', require('../../../assets/art/classes/ranger.webp'), 'UgJ@m:xu~UxaxtofWBWB~UWCofxaRjRkt6of'],
  ['classes', 'rogue', require('../../../assets/art/classes/rogue.webp'), 'UnNJzTt6~U%Lxuayayof~VofD*j[s:j[ofWB'],
  ['classes', 'sorcerer', require('../../../assets/art/classes/sorcerer.webp'), 'UXNJzSxZ~V%1?Gxtt7jF~WIpIo%2xuM|Rkof'],
  ['classes', 'warlock', require('../../../assets/art/classes/warlock.webp'), 'UcLM@s$U~UtLJNXM%Lsq~nNFoMxu=$$mjbNF'],
  ['classes', 'wizard', require('../../../assets/art/classes/wizard.webp'), 'UjKn3ZoJ~U%MxaWBWBof^*oLj[j?aeoft7WB'],
  ['items', 'battleaxe', require('../../../assets/art/items/battleaxe.webp'), 'UIR31M?H^c%Lt6%L%MD*=_RjD*xa~pIUE1?b'],
  ['items', 'blowgun', require('../../../assets/art/items/blowgun.webp'), 'UBRVk3~VrU?H?G_2t79Z=;ay4oM{~V4.M|~p'],
  ['items', 'breastplate', require('../../../assets/art/items/breastplate.webp'), 'UtNTRCxa~Voft7oefQWB?HaeRjt7oLWBxas:'],
  ['items', 'burglars-pack', require('../../../assets/art/items/burglars-pack.webp'), 'UcO|5-od~U-:%MayWBs:_2ofD*RkoJofofWB'],
  ['items', 'chain-mail', require('../../../assets/art/items/chain-mail.webp'), 'UwO3tRt6~VxuofoLj[WB?aj[IUay%Layayof'],
  ['items', 'chain-shirt', require('../../../assets/art/items/chain-shirt.webp'), 'UwNw1Mt6~VxtoKj[j[ay?Hj[IUay%Layj[of'],
  ['items', 'club', require('../../../assets/art/items/club.webp'), 'UGRCh=?a}.-oxZ%L%M9G-mj[9ZRj~VIVIU?b'],
  ['items', 'crossbow-hand', require('../../../assets/art/items/crossbow-hand.webp'), 'UTP?dQ-p~At6?Ht6RkRj^*axD*oeaeRjofxt'],
  ['items', 'crossbow-heavy', require('../../../assets/art/items/crossbow-heavy.webp'), 'UTQ058%L-P-:xtM{xut6~Vj[D%j[%M%LIVRj'],
  ['items', 'crossbow-light', require('../../../assets/art/items/crossbow-light.webp'), 'UHQ]cn-o=p?H-o-:%LD*~UWB9GRj^*9GIU_2'],
  ['items', 'dagger', require('../../../assets/art/items/dagger.webp'), 'UhPZMlxt~U%2xat7ofM{^*j[9ZayxuRjWBxt'],
  ['items', 'dart', require('../../../assets/art/items/dart.webp'), 'UnO:hBt6~V%Lt7ofofR*^*ofD%WBxaWBj[of'],
  ['items', 'diplomats-pack', require('../../../assets/art/items/diplomats-pack.webp'), 'UbN,F,oe~U-o%0j[j[oL~VoeE2WCjZayj]fQ'],
  ['items', 'dungeoneers-pack', require('../../../assets/art/items/dungeoneers-pack.webp'), 'UiOM$woe~U-p%LWBWBt7_2s:E1Rks:ofoeWB'],
  ['items', 'entertainers-pack', require('../../../assets/art/items/entertainers-pack.webp'), 'UjO3wZxt~Ut6-:f6Rjof?aoeIVWBt6ayWBj['],
  ['items', 'explorers-pack', require('../../../assets/art/items/explorers-pack.webp'), 'UgOf=6oe~U-:%LfPWBoe^*ofD*Rks.fQj[ay'],
  ['items', 'flail', require('../../../assets/art/items/flail.webp'), 'UoOM$wt6~V%2xtj[j[ay^*oeIUWCt6ayoej['],
  ['items', 'glaive', require('../../../assets/art/items/glaive.webp'), 'UDQ+sE^*}i%0-:%Lt79Z^cRj02t6~VIVM{?a'],
  ['items', 'greataxe', require('../../../assets/art/items/greataxe.webp'), 'UKRM6k-o^J-:oIRj%M%2$|t6IVM{~WxuE1IU'],
  ['items', 'greatclub', require('../../../assets/art/items/greatclub.webp'), 'UvN0xCs:~Vxuoej[t6j[?aj[IVj[xaj[ayay'],
  ['items', 'greatsword', require('../../../assets/art/items/greatsword.webp'), 'UARVqJ^*]e~V^*9Gt7~p=?kC4oRi~V-;M|01'],
  ['items', 'halberd', require('../../../assets/art/items/halberd.webp'), 'UERoyp?G]|^*%Lxt%MIU$wj[E2Rj~VRjE1%M'],
  ['items', 'half-plate-armor', require('../../../assets/art/items/half-plate-armor.webp'), 'UnPG1+xa~Wxuxaj@j[ay?afQIVfks:ayofof'],
  ['items', 'handaxe', require('../../../assets/art/items/handaxe.webp'), 'UHQJDd?G^c%2NFM{-p-:s7ayNGj?~W%LE19G'],
  ['items', 'hide-armor', require('../../../assets/art/items/hide-armor.webp'), 'UsN,k{xa~Vxtt7j[a|fQ?GayIVj[xuayofof'],
  ['items', 'javelin', require('../../../assets/art/items/javelin.webp'), 'UAQv8W^*#4^*^*_1j@D*#Ot602IV-oD%s:~V'],
  ['items', 'lance', require('../../../assets/art/items/lance.webp'), 'UXQ]TQxt~V%L~WoLD*WBjYaxkCj]RjayxuoL'],
  ['items', 'leather-armor', require('../../../assets/art/items/leather-armor.webp'), 'UpO:kJxa~Vxtt6j[j[ay-:j[IUWB%2ayj[of'],
  ['items', 'light-hammer', require('../../../assets/art/items/light-hammer.webp'), 'UHR2}F-o}:_2s.%L-pD*$xfPIVRj_2IUIo?a'],
  ['items', 'longbow', require('../../../assets/art/items/longbow.webp'), 'UBR{Vu^*z-~p^*t7ofIoros:M|M{^*WBR*xt'],
  ['items', 'longsword', require('../../../assets/art/items/longsword.webp'), 'UBQljy^+,l?G?Z-nxa9a#$f64;Rj^*D*IV~p'],
  ['items', 'mace', require('../../../assets/art/items/mace.webp'), 'UFRVqJ^*=WxZt4-:%M9F$dj[IVRj~VIUIU^+'],
  ['items', 'maul', require('../../../assets/art/items/maul.webp'), 'UJRCh=-o~8-:adM{-:-:$xoeIoWB~V%2IUD%'],
  ['items', 'morningstar', require('../../../assets/art/items/morningstar.webp'), 'ULQl,ixt~9^+-oIUa}?b$yt7IVM{^+%MM|9F'],
  ['items', 'net', require('../../../assets/art/items/net.webp'), 'UtNTUIoe~V%2%Lj@ofof^*j[E1ayRjj[WBWB'],
  ['items', 'padded-armor', require('../../../assets/art/items/padded-armor.webp'), 'UlM@Db%L~Vs.-pofayj[?GWBRjj[f5WBj[oe'],
  ['items', 'pike', require('../../../assets/art/items/pike.webp'), 'UTQ020t6~A?H%2ayofof^*xuD*IUxtofj[Rj'],
  ['items', 'plate-armor', require('../../../assets/art/items/plate-armor.webp'), 'UfQ058xa~U%L%Mj@RkfQ%1ayIojs%LoeRkWB'],
  ['items', 'potion-of-healing', require('../../../assets/art/items/potion-of-healing.webp'), 'UfP$:bxa~V%L%fj@V@j[-oj[IVaynijtoza|'],
  ['items', 'priests-pack', require('../../../assets/art/items/priests-pack.webp'), 'UoN^9qoe~V%L%2aya}of^+ofE1WBs:j[WBj@'],
  ['items', 'quarterstaff', require('../../../assets/art/items/quarterstaff.webp'), 'UERfE]?G~4_2?G%2t79GxUofIBM{?GRjWB-:'],
  ['items', 'rapier', require('../../../assets/art/items/rapier.webp'), 'UFQvUH_2=pjFxZ%L%MD%xAWBM|t6~pIVD%?a'],
  ['items', 'ring-mail', require('../../../assets/art/items/ring-mail.webp'), 'UxMjgXt6~Vxaoej@t7j[^*j[IVfQt6ayoLj['],
  ['items', 'scale-mail', require('../../../assets/art/items/scale-mail.webp'), 'UkP6mat7~Vxuxtt7ayM{^*jsD%j@xaRjoft7'],
  ['items', 'scholars-pack', require('../../../assets/art/items/scholars-pack.webp'), 'UiN,k{-p~Uae%MoeWBj@^*WBIUofxtayWBay'],
  ['items', 'scimitar', require('../../../assets/art/items/scimitar.webp'), 'UHRM0W?a~U%L~V-:IoD%$yRjIoxu?GIURk?a'],
  ['items', 'shield', require('../../../assets/art/items/shield.webp'), 'UeP6sot6~U%Loej[ofWB^*ayD*of%Layj[of'],
  ['items', 'shortbow', require('../../../assets/art/items/shortbow.webp'), 'UBRo$w~V]e%1_2%2WCD*-OM|D*%L?GM|xu%M'],
  ['items', 'shortsword', require('../../../assets/art/items/shortsword.webp'), 'UCRf2f?F~p^*?a-oxa9a~qs,E9R._2D*Ip~V'],
  ['items', 'sickle', require('../../../assets/art/items/sickle.webp'), 'UBRCh=~V}j?Gxs%L%MD*-OIVIp-p^*IU%L?a'],
  ['items', 'sling', require('../../../assets/art/items/sling.webp'), 'UYPsY3%1~UxtjYoft7WB?GWBIUt6%LWBj[of'],
  ['items', 'spear', require('../../../assets/art/items/spear.webp'), 'UARVtR~VvJ-o^*_2xuD%-4ay4oRP~VD*M|_3'],
  ['items', 'splint-armor', require('../../../assets/art/items/splint-armor.webp'), 'UZOfVpxZ~U%1xsazj[oe~UofE2WCs,oLofWC'],
  ['items', 'studded-leather-armor', require('../../../assets/art/items/studded-leather-armor.webp'), 'UxO3d#t7~Vxtxaj[a|ay?ajsE2ays:ayj[oL'],
  ['items', 'trident', require('../../../assets/art/items/trident.webp'), 'UQRCe+xt~V-;^*odIoRk?FodIVR*adWBxuxt'],
  ['items', 'war-pick', require('../../../assets/art/items/war-pick.webp'), 'UFRCPI?H~V?G%0-o-:9a-oWBIVWW~V9aNK~V'],
  ['items', 'warhammer', require('../../../assets/art/items/warhammer.webp'), 'UIR2_8?a^%%Lob-:-:E1^$IVD*xa~W9GIo_2'],
  ['items', 'whip', require('../../../assets/art/items/whip.webp'), 'UVP~[w-:~VofxtxaofNG~VWBE2WVxtM|WCxt'],
  ['races', 'dragonborn', require('../../../assets/art/races/dragonborn.webp'), 'UdJ*3HRj~V-nw]R+bHxZ^*ayafofkVaexZR+'],
  ['races', 'dwarf', require('../../../assets/art/races/dwarf.webp'), 'UaJ7mt%L~Uae%2s:RkNG?asmWCWCn%WVt6jt'],
  ['races', 'elf', require('../../../assets/art/races/elf.webp'), 'UsLzphs.^*xu%2f6WBj[~VofRjoeadj]t7j?'],
  ['races', 'gnome', require('../../../assets/art/races/gnome.webp'), 'UmN,oBxZ~V%Mt7f5o0kC~VbHIooeslbHozjF'],
  ['races', 'half-elf', require('../../../assets/art/races/half-elf.webp'), 'UtL;50bE_1%3n-WAj?oM~Vs:M|j[k8oft7fj'],
  ['races', 'half-orc', require('../../../assets/art/races/half-orc.webp'), 'UrMs}|t7~W%2oej[bHay^+j@M{kCt6fQs:j['],
  ['races', 'halfling', require('../../../assets/art/races/halfling.webp'), 'UxLD*;a}?H%1R*j@s:fQ~WofaykCxaj?ofbH'],
  ['races', 'human', require('../../../assets/art/races/human.webp'), 'UiK^vext?Gs:xaofjtay~Voet6t6s:aeofof'],
  ['races', 'tiefling', require('../../../assets/art/races/tiefling.webp'), 'UtN9]]t7~U%2jFbHofjG~VoeIVfkxun%oLW;'],
  ['schools', 'abjuration', require('../../../assets/art/schools/abjuration.webp'), 'UCGb#Gxu@;-ox]a{nhoL{Hn$F}fRwHjZkXof'],
  ['schools', 'conjuration', require('../../../assets/art/schools/conjuration.webp'), 'UPLW|Yxtfmt7~oofj[ofW@WV%0s:%Mj[t7jt'],
  ['schools', 'divination', require('../../../assets/art/schools/divination.webp'), 'UiM7cFt6~UxtWXayoef6^%oJNJofjDayt8kC'],
  ['schools', 'enchantment', require('../../../assets/art/schools/enchantment.webp'), 'UWKmkCs:~nxZxZfPbHj[?Zj[RQj[oef7s:j['],
  ['schools', 'evocation', require('../../../assets/art/schools/evocation.webp'), 'UoO3XwxZ.7xus.jZflfQ_Mj[wJs:xuj@s:oL'],
  ['schools', 'illusion', require('../../../assets/art/schools/illusion.webp'), 'UGG[A{s:~exaNEWUoeof~Sj?r|s;e.jbt3j='],
  ['schools', 'necromancy', require('../../../assets/art/schools/necromancy.webp'), 'U5Dc28%K+K={D*WC-.t6#DjbJ5oy~nofICaf'],
  ['schools', 'transmutation', require('../../../assets/art/schools/transmutation.webp'), 'URLgnDxa~C%epHfkr?j[^+t6RiV[#,jZS$bH'],
];

export const artManifest: Partial<Record<ArtKind, Record<string, ArtAsset>>> = {};
for (const [kind, id, source, blurhash] of ENTRIES) {
  (artManifest[kind] ??= {})[id] = { source, blurhash };
}
