// GENERATED by scripts/build-art-manifest.ts. Do not edit by hand.
// Empty until art is approved; ArtImage renders placeholders meanwhile.
import type { ImageSource } from 'expo-image';

export type ArtKind =
  | 'races'
  | 'classes'
  | 'schools'
  | 'backgrounds'
  | 'items'
  | 'portraits'
  | 'subclasses'
  | 'sigils'
  | 'ancestries';

export type ArtAsset = { source: ImageSource | number; blurhash: string };

export const artManifest: Partial<Record<ArtKind, Record<string, ArtAsset>>> = {};
