// GENERATED by scripts/build-art-manifest.ts. Do not edit by hand.
import type { ImageSource } from 'expo-image';

export type ArtKind =
  | 'races'
  | 'classes'
  | 'schools'
  | 'backgrounds'
  | 'items'
  | 'portraits'
  | 'subclasses'
  | 'sigils'
  | 'ancestries';

export type ArtAsset = { source: ImageSource | number; blurhash: string };

const ENTRIES: [ArtKind, string, number, string][] = [
  ['classes', 'barbarian', require('../../../assets/art/classes/barbarian.webp'), 'UrMs}{xa~WxuoJj[ofj@~WofIojtxaayj[ay'],
  ['classes', 'bard', require('../../../assets/art/classes/bard.webp'), 'UdK,{Lf%~U%Ls:WVofjb^*s:Rkj[t5oLafkB'],
  ['classes', 'cleric', require('../../../assets/art/classes/cleric.webp'), 'UwNJm:xt^*xaxZoeWCR*~VofM{j[t6ays:of'],
  ['races', 'dragonborn', require('../../../assets/art/races/dragonborn.webp'), 'UdJ*3HRj~V-nw]R+bHxZ^*ayafofkVaexZR+'],
  ['races', 'dwarf', require('../../../assets/art/races/dwarf.webp'), 'UaJ7mt%L~Uae%2s:RkNG?asmWCWCn%WVt6jt'],
  ['races', 'elf', require('../../../assets/art/races/elf.webp'), 'UsLzphs.^*xu%2f6WBj[~VofRjoeadj]t7j?'],
  ['races', 'gnome', require('../../../assets/art/races/gnome.webp'), 'UmN,oBxZ~V%Mt7f5o0kC~VbHIooeslbHozjF'],
  ['races', 'half-elf', require('../../../assets/art/races/half-elf.webp'), 'UtL;50bE_1%3n-WAj?oM~Vs:M|j[k8oft7fj'],
  ['races', 'half-orc', require('../../../assets/art/races/half-orc.webp'), 'UrMs}|t7~W%2oej[bHay^+j@M{kCt6fQs:j['],
  ['races', 'halfling', require('../../../assets/art/races/halfling.webp'), 'UxLD*;a}?H%1R*j@s:fQ~WofaykCxaj?ofbH'],
  ['races', 'human', require('../../../assets/art/races/human.webp'), 'UiK^vext?Gs:xaofjtay~Voet6t6s:aeofof'],
  ['races', 'tiefling', require('../../../assets/art/races/tiefling.webp'), 'UtN9]]t7~U%2jFbHofjG~VoeIVfkxun%oLW;'],
];

export const artManifest: Partial<Record<ArtKind, Record<string, ArtAsset>>> = {};
for (const [kind, id, source, blurhash] of ENTRIES) {
  (artManifest[kind] ??= {})[id] = { source, blurhash };
}
