/**
 * Packs approved art into the app: art/raw -> assets/art/<kind>/<id>.webp,
 * plus blurhash placeholders, and regenerates src/content/art/manifest.ts.
 *
 *   npx tsx scripts/build-art-manifest.ts            # only assets listed in art/approved.json
 *   npx tsx scripts/build-art-manifest.ts --preview  # also variant 1 of anything not yet approved
 *
 * art/approved.json maps "<kind>/<id>" to the chosen variant number, e.g. { "races/dwarf": 2 }.
 */
import { encode } from 'blurhash';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import sharp from 'sharp';

const ROOT = resolve(__dirname, '..');
const RAW = join(ROOT, 'art', 'raw');
const OUT = join(ROOT, 'assets', 'art');

// Display sizes at ~3x density: full-width cards and thumbnail icons.
const SIZES = { card: { width: 900, height: 1200 }, icon: { width: 384, height: 384 } };

const { values } = parseArgs({ options: { preview: { type: 'boolean', default: false } } });

async function blurhashOf(file: string) {
  const { data, info } = await sharp(file).resize(32, 32, { fit: 'inside' }).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  return encode(new Uint8ClampedArray(data), info.width, info.height, 4, 4);
}

async function main() {
  const approvedFile = join(ROOT, 'art', 'approved.json');
  const approved: Record<string, number> = existsSync(approvedFile) ? JSON.parse(readFileSync(approvedFile, 'utf8')) : {};

  // Which variant to ship for each asset.
  const chosen = new Map<string, number>(Object.entries(approved));
  if (values.preview && existsSync(RAW)) {
    for (const file of readdirSync(RAW)) {
      const m = file.match(/^([a-z]+)-(.+)-(\d+)\.png$/);
      if (!m) continue;
      const key = `${m[1]}/${m[2]}`;
      if (!chosen.has(key) || (!approved[key] && Number(m[3]) < chosen.get(key)!)) chosen.set(key, Number(m[3]));
    }
  }

  const entries: string[] = [];
  for (const [key, variant] of [...chosen].sort()) {
    const [kind, id] = key.split('/');
    const src = join(RAW, `${kind}-${id}-${variant}.png`);
    if (!existsSync(src)) {
      console.warn(`missing ${src}`);
      continue;
    }
    const meta = await sharp(src).metadata();
    const size = meta.width === meta.height ? SIZES.icon : SIZES.card;
    mkdirSync(join(OUT, kind), { recursive: true });
    const dest = join(OUT, kind, `${id}.webp`);
    await sharp(src).resize(size.width, size.height, { fit: 'cover' }).webp({ quality: 82 }).toFile(dest);
    const hash = await blurhashOf(dest);
    entries.push(`  ['${kind}', '${id}', require('../../../assets/art/${kind}/${id}.webp'), '${hash}'],`);
  }

  writeFileSync(
    join(ROOT, 'src', 'content', 'art', 'manifest.ts'),
    `// GENERATED by scripts/build-art-manifest.ts. Do not edit by hand.
import type { ImageSource } from 'expo-image';

export type ArtKind =
  | 'races'
  | 'classes'
  | 'schools'
  | 'backgrounds'
  | 'items'
  | 'portraits'
  | 'subclasses'
  | 'sigils'
  | 'ancestries';

export type ArtAsset = { source: ImageSource | number; blurhash: string };

const ENTRIES: [ArtKind, string, number, string][] = [
${entries.join('\n')}
];

export const artManifest: Partial<Record<ArtKind, Record<string, ArtAsset>>> = {};
for (const [kind, id, source, blurhash] of ENTRIES) {
  (artManifest[kind] ??= {})[id] = { source, blurhash };
}
`,
  );
  console.log(`${entries.length} assets packed into assets/art and the manifest`);
}

main();
