/**
 * Finishes the web export for GitHub Pages (run after `npx expo export -p web`):
 * - home-screen app tags and a web app manifest (iPhone "Add to Home Screen")
 * - 404.html = index.html, so deep links like /inkbound/character/abc load the app
 * - .nojekyll, or GitHub Pages hides the _expo/ folder that holds the app code
 * - sw.js: a service worker that caches every file for offline use; the cache
 *   name is a fingerprint of the build, so a new deploy replaces the old cache
 *
 *   EXPO_PUBLIC_BASE_URL=/inkbound npx expo export -p web && npx tsx scripts/prepare-web.ts
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const DIST = resolve(__dirname, '..', 'dist');
const BASE = process.env.EXPO_PUBLIC_BASE_URL ?? '';

function files(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? files(path) : [path];
  });
}

// 1. Home-screen app tags.
const indexPath = join(DIST, 'index.html');
let html = readFileSync(indexPath, 'utf8');
const head = [
  `<link rel="manifest" href="${BASE}/manifest.webmanifest">`,
  `<link rel="apple-touch-icon" href="${BASE}/apple-touch-icon.png">`,
  '<meta name="apple-mobile-web-app-capable" content="yes">',
  '<meta name="mobile-web-app-capable" content="yes">',
  '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">',
  '<meta name="apple-mobile-web-app-title" content="Inkbound">',
  '<meta name="theme-color" content="#16120F">',
].join('\n    ');
html = html.replace(/<title>.*?<\/title>/, '<title>Inkbound</title>').replace('</head>', `    ${head}\n  </head>`);
writeFileSync(indexPath, html);

writeFileSync(
  join(DIST, 'manifest.webmanifest'),
  JSON.stringify(
    {
      name: 'Inkbound',
      short_name: 'Inkbound',
      description: 'A visual character creator and character sheet for 5e tabletop games.',
      start_url: `${BASE}/`,
      scope: `${BASE}/`,
      display: 'standalone',
      orientation: 'portrait',
      background_color: '#16120F',
      theme_color: '#16120F',
      icons: [
        { src: `${BASE}/icon-192.png`, sizes: '192x192', type: 'image/png' },
        { src: `${BASE}/icon-512.png`, sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
      ],
    },
    null,
    2,
  ),
);

// 2. Deep links and 3. Jekyll.
writeFileSync(join(DIST, '404.html'), html);
writeFileSync(join(DIST, '.nojekyll'), '');

// 4. Offline cache: every built file (except the 404 copy and dotfiles).
const assets = files(DIST)
  .map((f) => relative(DIST, f).replace(/\\/g, '/'))
  .filter((f) => f !== '404.html' && !f.startsWith('.') && f !== 'sw.js')
  .sort();
const fingerprint = createHash('sha256');
for (const f of assets) fingerprint.update(f).update(readFileSync(join(DIST, f)));
const cacheName = `inkbound-${fingerprint.digest('hex').slice(0, 12)}`;
const urls = [`${BASE}/`, ...assets.map((f) => `${BASE}/${f}`)];

writeFileSync(
  join(DIST, 'sw.js'),
  `// Generated by scripts/prepare-web.ts. Caches the whole app for offline use.
const CACHE = ${JSON.stringify(cacheName)};
const URLS = ${JSON.stringify(urls)};
const INDEX = ${JSON.stringify(`${BASE}/index.html`)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(URLS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('inkbound-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  // App pages (e.g. /character/abc) all load the same single-page app.
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.match(INDEX)));
    return;
  }
  event.respondWith(caches.match(request, { ignoreSearch: true }).then((hit) => hit || fetch(request)));
});
`,
);

const size = assets.reduce((n, f) => n + statSync(join(DIST, f)).size, 0);
console.log(`prepared dist/ for ${BASE || '/'}: ${assets.length} files (${(size / 1e6).toFixed(1)} MB) cached as ${cacheName}`);
